modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="http://github.com/Kamefrede/nattiesbegone"
license="MIT License"
[[mods]]
modId="nattiesbegone"
version="${file.jarVersion}"
displayName="Natties Begone!"
credits="Commissioned by dani, delivered with love by Kamefrede"
authors="Kamefrede, dani"
description='''
Have you ever wanted to stop fish from spawning from buckets? Me neither, but this mod allows you to do it.
Control the conditions of which mob types can spawn with this one simple to use mod.
'''

[[dependencies.nattiesbegone]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.22,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nattiesbegone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
